
clone_depth: 5

environment:
  matrix:
  # node.js
    - nodejs_version: "6"
    - nodejs_version: "4"
    - nodejs_version: "0.12"

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off

version: "{build}"
