
clone_depth: 5

environment:
  matrix:
  - nodejs_version: "10"
    TEST: "npm run test"
  - nodejs_version: "12"
    TEST: "npm run test"

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version x64
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install

test_script:
  - node --version
  - npm --version
  - cmd: "%TEST%"

build: off

version: "{build}"
